### ISSUE TITLE
App is broken with 1.6.0.rc.1 and compass 0.11.1

### ISSUE THREAD

**Issue by aflatter** [sproutcore/Todos-Example#7]
Looks like some problem with compass.

Dependencies:

```
Using abstract (1.0.0) 
Using chunky_png (1.1.0) 
Using fssm (0.2.7) 
Using sass (3.1.1) 
Using compass (0.11.1) 
Using daemons (1.1.3) 
Using erubis (2.6.6) 
Using eventmachine (0.12.10) 
Using extlib (0.9.15) 
Using haml (3.1.1) 
Using json_pure (1.4.6) 
Using rack (1.2.2) 
Using thin (1.2.11) 
Using thor (0.14.6) 
Using sproutcore (1.6.0.rc.1) 
Using bundler (1.0.10) 
```

Output of `bundle exec sc-server` when doing a request:

```
SproutCore v1.6.0.rc.1 Development Server
Starting server at http://0.0.0.0:4021 in debug mode
To quit sc-server, press Control-C
>> Thin web server (v1.2.11 codename Bat-Shit Crazy)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:4021, CTRL+C to stop
Sass::SyntaxError: Undefined mixin 'border-radius'.
    tmp/chance/aca63e2d9df1febb6dd18e7567c84d9c.scss:10:in `border-radius'
    tmp/chance/aca63e2d9df1febb6dd18e7567c84d9c.scss:10
    chance_main.css:2
    ....
```

**Comment by publickeating** [comment]
There were some deprecations from Compass 0.10.x to 0.11.x, I will check it out and update the CSS.

Thanks for the tip!

**Comment by publickeating** [comment]
Actually, I’m afraid I can’t reproduce a problem.  I tried with my Gemfile as:

```
gem 'sproutcore', :git => 'https://github.com/sproutcore/abbot.git'
```

and

```
gem 'sproutcore', :git => 'https://github.com/sproutcore/abbot.git', :tag => 'REL-1.6.0.rc.1’
```

Could you please verify that you’ve pulled the latest Todos code?

**Comment by aflatter** [comment]
I just verified that the repository is up to date. This is what my Gemfile looked like:

```
gem 'sproutcore', '1.6.0.rc.1'
gem 'chunky_png', '1.1.0'

source :rubygems
```

I had to explicitly pin chunky_png because 1.2.0 got activated.

I tried again with REL-1.6.0.rc.1 which gives me another error:

```
WARN 23:18:19.006 ~ Could not find target sproutcore/core_foundation that is required by /todos 
WARN 23:18:19.006 ~ Could not find target sproutcore/empty_theme that is required by /todos 
WARN 23:18:19.006 ~ Could not find target sproutcore/core_foundation that is required by /todos 
RuntimeError: html_builder could not find a layout file for sproutcore:lib/index.rhtml
        /home/x/.rvm/gems/ruby-1.9.2-p136/bundler/gems/abbot-62abfbc5e632/lib/sproutcore/builders/html.rb:107:in `render'
        /home/x/.rvm/gems/ruby-1.9.2-p136/bundler/gems/abbot-62abfbc5e632/lib/sproutcore/builders/html.rb:121:in `build'
        /home/x/.rvm/gems/ruby-1.9.2-p136/bundler/gems/abbot-62abfbc5e632/lib/sproutcore/builders/base.rb:35:in `build'
        /home/x/.rvm/gems/ruby-1.9.2-p136/bundler/gems/abbot-62abfbc5e632/lib/buildtasks/build.rake:58:in `block (2 levels) in define!'
        /home/x/.rvm/gems/ruby-1.9.2-p136/bundler/gems/abbot-62abfbc5e632/lib/sproutcore/buildfile/task.rb:231:in `call'
        /home/x/.rvm/gems/ruby-1.9.2-p136/bundler/gems/abbot-62abfbc5e632/lib/sproutcore/buildfile/task.rb:231:in `block in execute'
```

**Comment by wagenet** [comment]
This should be fixed in RC2.
